services:
  - type: web
    name: ml-sales-prediction
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
